CREATE TABLE user_info (user_id INTEGER NOT NULL, AGE INTEGER, CREATEDDATE TIMESTAMP, EMAIL VARCHAR(255), first_name VARCHAR(255), GENDER VARCHAR(255), IMAGEDATA BYTEA, last_name VARCHAR(255), PHONE VARCHAR(255), user_name VARCHAR(255), XMLTEXT TEXT, PRIMARY KEY (user_id))
CREATE TABLE password_details (user_id INTEGER NOT NULL, PASSWORD VARCHAR(255), sec_ans_1 VARCHAR(255), sec_ans_2 VARCHAR(255), sec_ques_1 VARCHAR(255), sec_ques_2 VARCHAR(255), PRIMARY KEY (user_id))
ALTER TABLE password_details ADD CONSTRAINT FK_password_details_user_id FOREIGN KEY (user_id) REFERENCES user_info (user_id)
CREATE SEQUENCE user_seq START WITH 1
CREATE SEQUENCE user_seq START WITH 1
